name:                split-morphism
version:             0.1.0.0
github:              "gvolpe/split-morphism"
license:             BSD3
author:              "Gabriel Volpe"
maintainer:          "volpegabriel@gmail.com"
copyright:           "2019 Gabriel Volpe"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Split Epimorphisms and Monomorphisms
category:            Data, Lenses, Generics

description:         Please see the README on GitHub at <https://github.com/gvolpe/split-morphism#readme>

dependencies:
- base >= 4.7 && < 5
- invariant >= 0.5.1 && < 0.6
- lens >= 4.17 && < 4.18
- mtl >= 2.2.2 && < 2.3
- QuickCheck >= 2.12.6 && < 2.13

library:
  source-dirs: src

tests:
  split-morphism-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wcompat
    - -Widentities
    - -Wredundant-constraints
    - -Wmissing-export-lists
    - -Wpartial-fields
    dependencies:
    - split-morphism

