version: 2.1

orbs:
  haskell: haskell-works/haskell-build@1.4.1

workflows:
  build_split_morphism:
    jobs:
      - haskell/build:
          name: GHC 8.6.3
          executor: haskell/ghc-8_6_3
          cabal-file: split-morphism.cabal

